[
    ['\\bAl je ramen gaan eruit\\b', ['Je hele netwerk gaat eruit']],
    ['\\bAls iemand je niet heeft verstaan\\b', ['ja oor!']],
    ['\\bAls iets mooi is\\b', ['Dat is maar nie mooi']],
    ['\\bals je een klein presentje meeneemt\\b', ['uts wènnig mar ut kom uit un goed harret']],
    ['\\bAls je iemand niet gelooft\\b', ['Juh zuster met die dikke duim']],
    ['\\bdie heeft een katheter\\b', ['die heef een container op ze buik']],
    ['\\been lekke band\\b', ['een lekke peip']],
    ['\\bEen lelijk meisje\\b', ['Die hep model gestaan voor van der Luyt']],
    ['\\been vrouw die zwanger is\\b', ['juh, daar loop een buik met benen']],
    ['\\bHeb je praatjes\\b', ['Had je spassies dan']],
    ['\\bHet zwaard van Damocles\\b', ['Het zwaard van Damascus']],
    ['\\bHij is overleden\\b', ['Hij heb een tuin op ze buik']],
    ['\\bHij is overleden\\b', ['Hij is een zandwinkel begonnuh']],
    ['\\bHou toch op zeg!\\b', ['Juh, sterref lekkar!']],
    ['\\bIemand is niet aardig\\b', ['Hij hep een goed hart. Ut had alleen gekookt op sun rug moete hange. Zo hoog dat de honde erbij kunne.']],
    ['\\bik trap je ramen in met een voetbal\\b', ['ik teer je netten in met een bledder']],
    ['\\bik vind je niet aardig\\b', ['juh, pleur lekka je graf in']],
    ['\\bIk zit vol (eten)\\b', ['Ik zit voor de brug']],
    ['\\bJe kan aan het gas!\\b', ['Je ken an \'t gast !']],
    ['\\bniet praten maar doen.\\b', ['Niet mare juh, de Mare ligt achter de haarlemmerstraat']],
    ['\\bonder in de kast\\b', ['in de laagte']],
    ['\\bongelijk\\b', ['ongelijk is een boggel']],
    ['\\bongelijk hebben\\b', ['ongelijk is een boggel']],
    ['\\bpraatjes\\b', ['spassies']],
    ['\\bSchelden\\b', ['Je ken een kind krijgen met een roodkopere kop dan ken je je de kolere poetsen juh!']],
    ['\\bSloof je niet zo uit\\b', ['Juh, ken je nog wat met je ooren dan?']],
    ['\\btegen iemand zeggen dat hij niet moet twijfelen (veel maar zeggen)\\b', ['De mare is gedempt']],
    ['\\bWat heb je gedaan?\\b', ['Wat hebbie uitgevrote dan?']],
    ['\\bwat is er met je aan de hand?\\b', ['Juh, wat hebbie dan?']],
    ['\\bwe gingen nog even de (3 oktober) kermis op\\b', ['we gongen nog effuh ut veld op.']],
    ['\\bzwanger maken\\b', ['Met jong schoppen']],
    ['\\b2 koffie 2 koeken\\b', ['2 pleur 2 scheerbak']],
    ['\\b3 oktoberfeest\\b', ['driektober']],
    ['\\baan\\b', ['an']],
    ['\\baanrecht\\b', ['rechtbank']],
    ['\\baanstonds\\b', ['aas']],
    ['\\bacht\\b', ['ach']],
    ['\\bafvalbak\\b', ['kiepelton']],
    ['\\bafvalcontainer\\b', ['vlikobak']],
    ['\\bafvaljager\\b', ['sjappetouwer']],
    ['\\bAkkefietje\\b', ['Attekfietje']],
    ['\\bals je een rooie ziet zeggen we\\b', ['juh rooooie vreet je haare op dur komp een stierr an']],
    ['\\bambulance\\b', ['stoffer en blik']],
    ['\\bapart\\b', ['ampart']],
    ['\\bbagagedrager\\b', ['lasdrager']],
    ['\\bbangerik\\b', ['schrikkepuit', 'broekescheitert']],
    ['\\bbehelpen\\b', ['beleie']],
    ['\\bbiertje\\b', ['pijpie']],
    ['\\bbieten\\b', ['kroten is niet specifiek Leids.']],
    ['\\bbijna\\b', ['aanstenz', 'bekant', 'temet']],
    ['\\bbinnenkort\\b', ['aas', 'termee']],
    ['\\bBoisotkade\\b', ['Biesjotkade']],
    ['\\bbosjes\\b', ['bossies']],
    ['\\bbrancard\\b', ['brrandkar']],
    ['\\bBril\\b', ['Fok']],
    ['\\bBromfietscertificaat\\b', ['Bromfietsfertisikaat']],
    ['\\bbrommer\\b', ['brommert']],
    ['\\bbureaucratie\\b', ['bureaucreatie']],
    ['\\bCaravan\\b', ['Kerneven']],
    ['\\bcarpaccio\\b', ['carpatio']],
    ['\\bClown\\b', ['Kloon']],
    ['\\bcondom\\b', ['regen jasie']],
    ['\\bcriminele\\b', ['crimmenele']],
    ['\\bDashbordkastje\\b', ['Bordeskastje']],
    ['\\bde Decima\\b', ['de Dees']],
    ['\\bde groeten\\b', ['du groetuh']],
    ['\\bDe markt\\b', ['De mart']],
    ['\\bdementeert\\b', ['mediteert']],
    ['\\bDie is overleden\\b', ['Die is een zandwinkel begonnuh']],
    ['\\bdik persoon\\b', ['kadijer']],
    ['\\bdik zijn\\b', ['as kannera']],
    ['\\bdikke buik\\b', ['spierbuik']],
    ['\\bdikke kin\\b', ['kanis']],
    ['\\bdikke kop\\b', ['bledder']],
    ['\\bdood\\b', ['met de pik omhoog liggen']],
    ['\\bdood zijn\\b', ['met de pisser omhoog liggen']],
    ['\\bdoods hoofd\\b', ['knijne kop']],
    ['\\bdrinken\\b', ['zuipe']],
    ['\\bdronken\\b', ['aan de lal zijn']],
    ['\\bduif\\b', ['koekerroe']],
    ['\\bdwaas\\b', ['koekerroe']],
    ['\\been jongen uit de wijk de kooi\\b', ['kooiboy']],
    ['\\been klap\\b', ['een drijver']],
    ['\\been klap\\b', ['bamzaaier']],
    ['\\been naar persoon\\b', ['een etter', 'een etterbol', 'juh darruhm', 'klerenleijer']],
    ['\\been raam ingooien\\b', ['ik teer je net in']],
    ['\\beerlijk\\b', ['eeluk']],
    ['\\beigenwijze veldworm\\b', ['darm']],
    ['\\beikel\\b', ['darm']],
    ['\\belke keer\\b', ['tellekes']],
    ['\\benige\\b', ['enigste']],
    ['\\bErker\\b', ['erkel']],
    ['\\beten\\b', ['essen']],
    ['\\beuro\\b', ['uro']],
    ['\\bfabriek\\b', ['fambriek']],
    ['\\bFamilie\\b', ['Famielje']],
    ['\\bfeestneus\\b', ['bamboezuer']],
    ['\\bGa weg!\\b', ['pleurttop juh! Teer op!']],
    ['\\bgas\\b', ['gast']],
    ['\\bgegooid\\b', ['gepleurd']],
    ['\\bgehakt\\b', ['gehak']],
    ['\\bgek\\b', ['lèhperd', 'zot', 'halve zool']],
    ['\\bgek iemand\\b', ['zottuhklos']],
    ['\\bgekke\\b', ['gare']],
    ['\\bgekkigheid\\b', ['zottighèd']],
    ['\\bgeld\\b', ['groot']],
    ['\\bgemerkt\\b', ['gemorreke']],
    ['\\bgezicht\\b', ['bekkie', 'porrum', 'porum', 'raap']],
    ['\\bglas port\\b', ['glasie poort']],
    ['\\bglibber\\b', ['glipper']],
    ['\\bgluren\\b', ['neuzen']],
    ['\\bgoede\\b', ['goeie']],
    ['\\bgoedemorgen\\b', ['mogguh']],
    ['\\bgozer\\b', ['gozert']],
    ['\\bgracht\\b', ['gurwacht']],
    ['\\bgrappig\\b', ['lagguh juh']],
    ['\\bgratis, kostenloos\\b', ['voor nop']],
    ['\\bgroeten\\b', ['spreken']],
    ['\\bgrof vuil\\b', ['de kraak']],
    ['\\bgrote kin\\b', ['cente bak']],
    ['\\bgutsen\\b', ['gonzen']],
    ['\\bgutst\\b', ['gonst']],
    ['\\bgynaecoloog\\b', ['kierekijker']],
    ['\\bHaarlemmerstraat\\b', ['Haarmestraat']],
    ['\\bHangsnor\\b', ['Lorresnor']],
    ['\\bharing\\b', ['katwijker']],
    ['\\bhartinfarct\\b', ['hardvarkuh']],
    ['\\bhartinfarct\\b', ['hartinvaasie']],
    ['\\bheb je\\b', ['hebbie']],
    ['\\bheeft\\b', ['heb']],
    ['\\bhet\\b', ['ut']],
    ['\\bHet Lisser veerhuis\\b', ['Ut Lissa virhuiz']],
    ['\\bhet stinkt\\b', ['\'t meurt']],
    ['\\bhet ziekenfonds\\b', ['\'t fonkst', 'het ziekefondst']],
    ['\\bhij is dood\\b', ['zijn gat is koud']],
    ['\\bhij is dronken\\b', ['als een maleijer']],
    ['\\bhij zei\\b', ['hij zee']],
    ['\\bhoofd\\b', ['bledder', 'harsus', 'bakkus']],
    ['\\bhou je mond dicht\\b', ['houtje kokurrrr']],
    ['\\bhuilen\\b', ['janken']],
    ['\\bik ga\\b', ['ik peert \'m']],
    ['\\bIk heb met hem gezoend\\b', ['Ik ben met hem gegaan']],
    ['\\bik hoop dat je\\b', ['mag lije dat je']],
    ['\\bimperiaal\\b', ['imperium']],
    ['\\bin coma zijn\\b', ['in croma leggen']],
    ['\\bin de brand\\b', ['in de hens']],
    ['\\bin het water\\b', ['in de maajem']],
    ['\\bingeslikt\\b', ['ingeslokke']],
    ['\\bintensive care\\b', ['intensieve karee']],
    ['\\bje\\b', ['juh']],
    ['\\bje moeder\\b', ['je ouwe moer']],
    ['\\bje moet betale\\b', ['schuive ju']],
    ['\\bjenever\\b', ['jainever']],
    ['\\bjij\\b', ['juh']],
    ['\\bjoh\\b', ['juh']],
    ['\\bjuh\\b', ['jij']],
    ['\\bkaal persoon\\b', ['Kaleneet']],
    ['\\bkaal worden\\b', ['juh ! je binnenbal komt ur doorheen']],
    ['\\bKale kop\\b', ['Bledder']],
    ['\\bkale kop\\b', ['kane kop', 'schedel']],
    ['\\bkan\\b', ['ken']],
    ['\\bKan/ken of kun je\\b', ['Kejje']],
    ['\\bkantine\\b', ['karremetiene']],
    ['\\bkarper\\b', ['karreper']],
    ['\\bkatholiek zijn\\b', ['Van \'t houtje zijn']],
    ['\\bKatwijker\\b', ['Katteker']],
    ['\\bkauwgom\\b', ['kàgun']],
    ['\\bkermis\\b', ['kerremus']],
    ['\\bkijk eens\\b', ['kijkteris']],
    ['\\bkin\\b', ['klus']],
    ['\\bkinderwagen\\b', ['larvenbak', 'larvenkar']],
    ['\\bKlap in je gezicht\\b', ['n kuister op je kanis /op die dikke bledder van juh']],
    ['\\bklap op je gezicht\\b', ['hijs op je treiter']],
    ['\\bKlap voor je kop\\b', ['Slag vor juh aambeelts']],
    ['\\bKledingkast\\b', ['Klerekast']],
    ['\\bKleine visjes\\b', ['Speldaasies']],
    ['\\bklootzak\\b', ['klerelijer']],
    ['\\bknaapje van kleding\\b', ['klerehanger']],
    ['\\bknikker/ vuistslag\\b', ['kuister']],
    ['\\bkomt dat\\b', ['komp ut']],
    ['\\bkoprol\\b', ['omduikeltje']],
    ['\\bkorset\\b', ['korsjet']],
    ['\\bKotsen\\b', ['over je zuiger']],
    ['\\bkraslot\\b', ['krasloot']],
    ['\\bKrij nu wat\\b', ['krijg het lazerus']],
    ['\\bkrijg het heen en weer\\b', ['juh krijg een ballutjuh']],
    ['\\bKroeg\\b', ['Keilewinkel']],
    ['\\bkromme neus\\b', ['zinksnijer']],
    ['\\bKun je dat wel missen\\b', ['Kejje dat lije dan']],
    ['\\blangs\\b', ['langes']],
    ['\\blastdrager\\b', ['lasdrager']],
    ['\\blastpost\\b', ['parg']],
    ['\\blederen bal\\b', ['Bledder']],
    ['\\bLegitimatiebewijs\\b', ['Legemetatiebewijs']],
    ['\\bleidenaar\\b', ['glibber']],
    ['\\bLeids\\b', ['Leis']],
    ['\\blelijk gezicht\\b', ['poffertjes porum']],
    ['\\bleraren\\b', ['leraars']],
    ['\\bleren voetbal\\b', ['bledder']],
    ['\\bLeukerd\\b', ['Nar']],
    ['\\blichaam\\b', ['lijer']],
    ['\\bLije\\b', ['missen']],
    ['\\bmaisonnette\\b', ['majorette']],
    ['\\bMajorettemeisje\\b', ['Kooigirl']],
    ['\\bmank lopen\\b', ['horrel']],
    ['\\bMariahoeve\\b', ['Maria Ho Effe']],
    ['\\bmarinade\\b', ['marmelade']],
    ['\\bmasker\\b', ['mombakkus']],
    ['\\bmeer dan\\b', ['meer als']],
    ['\\bmeid\\b', ['mè, mèd', 'Mêh']],
    ['\\bmeisje\\b', ['meissie']],
    ['\\bmep\\b', ['zaaier']],
    ['\\bmeteen\\b', ['bedeen']],
    ['\\bmijn god\\b', ['jeezus kristus']],
    ['\\bmoeilijk\\b', ['moeluk']],
    ['\\bmoet\\b', ['mot']],
    ['\\bmoeten\\b', ['motten']],
    ['\\bmond\\b', ['meelkokûr']],
    ['\\bnaar iemand\\b', ['tirringlijer']],
    ['\\bnaar mijn idee wel\\b', ['voormeinpart welja']],
    ['\\bnaar persoon\\b', ['longlijer']],
    ['\\bNar\\b', ['Leukerd']],
    ['\\bnederlandse\\b', ['nederlanse']],
    ['\\bniet eens\\b', ['genees']],
    ['\\bnuance\\b', ['nowenze']],
    ['\\bochtendjas\\b', ['pingwaar']],
    ['\\bomdat\\b', ['omda']],
    ['\\bongelijk\\b', ['onkant']],
    ['\\bongelofelijk\\b', ['niette filme']],
    ['\\bop je gezicht gaan\\b', ['op je plaat gaan']],
    ['\\bop rotten\\b', ['op teeruh']],
    ['\\bopgeborgen\\b', ['opgeborrege']],
    ['\\bopgemaakt meisje\\b', ['poppeka']],
    ['\\boplichter\\b', ['laaienlichter']],
    ['\\bopschepper\\b', ['begeur']],
    ['\\bover een poosje\\b', ['metteraas']],
    ['\\boverlijden\\b', ['De pijp uit gaan ( ook Amsterdam)']],
    ['\\bparaplu\\b', ['plu', 'bledderdrooghouwer', 'bledderdrooghouer']],
    ['\\bpardon\\b', ['hee juhh']],
    ['\\bpassant\\b', ['pesant']],
    ['\\bplaaggeest\\b', ['parg']],
    ['\\bplastic\\b', ['plestikke']],
    ['\\bpolitie\\b', ['pliesie', 'Popo']],
    ['\\bpolitieagent\\b', ['klabak', 'een luis']],
    ['\\bpolitieagenten\\b', ['de kit']],
    ['\\bpolitiebureau\\b', ['pliesiebro']],
    ['\\bPostduif\\b', ['Dakscheiter']],
    ['\\bprofessor\\b', ['perfesser']],
    ['\\bpsychiater\\b', ['spiegiater']],
    ['\\bpsycholoog\\b', ['spycholoog']],
    ['\\bpuistenkop\\b', ['tietuhbek']],
    ['\\bput\\b', ['kolk']],
    ['\\bput/putdeksel\\b', ['kolk']],
    ['\\bputdeksel\\b', ['kolk']],
    ['\\braam\\b', ['net']],
    ['\\bramen\\b', ['nettuh']],
    ['\\brare man/vrouw\\b', ['achteleke']],
    ['\\brasechte Leidenaar\\b', ['Lèdse Glibber']],
    ['\\bReanimatie\\b', ['Reamikasie']],
    ['\\bregen\\b', ['bledder']],
    ['\\brennen\\b', ['renne']],
    ['\\breproductie\\b', ['reductie']],
    ['\\brimpel hoofd\\b', ['krater kop']],
    ['\\broodharige\\b', ['arebei']],
    ['\\broofoverval\\b', ['rowowerwal', 'rowowerfwal', 'wroofowverwval']],
    ['\\brot griet\\b', ['me vullus wijf']],
    ['\\brot op\\b', ['tief op']],
    ['\\brot op joh!\\b', ['teer op juh!']],
    ['\\brotgriet\\b', ['me vulles leier']],
    ['\\brotonde\\b', ['rontonde']],
    ['\\brotzooi\\b', ['tinnefzooi']],
    ['\\bschaamhaar\\b', ['spinnerag']],
    ['\\bslager\\b', ['knors']],
    ['\\bslechte jongen\\b', ['kruize duiker']],
    ['\\bsloot\\b', ['maaium']],
    ['\\bsloot\\b', ['plomp']],
    ['\\bsnol\\b', ['stinkdeken']],
    ['\\bspagettibandjes\\b', ['hemeseeltjes']],
    ['\\bspinazie\\b', ['glip']],
    ['\\bstaat\\b', ['stot']],
    ['\\bstelen\\b', ['klauwen', 'rauzen']],
    ['\\bstoel\\b', ['karpoo']],
    ['\\bstrobreed\\b', ['strookbreed']],
    ['\\bsuffert\\b', ['klootzak']],
    ['\\btomos (bromfiets)\\b', ['tomas (brommert)']],
    ['\\btongzoenen\\b', ['kopkluiven']],
    ['\\btouwfabriek\\b', ['touwbaan']],
    ['\\btumor\\b', ['timor']],
    ['\\bTumor\\b', ['Tumor']],
    ['\\btwee koffie twee koeken\\b', ['twee pluer twee scheerbakke']],
    ['\\btwijfelen\\b', ['staan in de dreig']],
    ['\\bUitdagen\\b', ['uitheilige']],
    ['\\bvallen\\b', ['teren', 'pleuren', 'tiefen']],
    ['\\bverader\\b', ['vuile keel']],
    ['\\bverraden\\b', ['verraaie']],
    ['\\bvervelend persoon\\b', ['darm', 'juh bloedpoepur !']],
    ['\\bvicieuze cirkel\\b', ['visuele cirkel']],
    ['\\bvideoband\\b', ['fidiofillum']],
    ['\\bviezerik\\b', ['viezik', 'goorlap']],
    ['\\bvinder\\b', ['vindert']],
    ['\\bvoetbal\\b', ['bledder']],
    ['\\bvoetballen\\b', ['voebelluh']],
    ['\\bvogelkooi\\b', ['vogelekooi']],
    ['\\bvuurpijlen\\b', ['fuupelle']],
    ['\\bWat gaan we doen?/ Wat zijn de plannen?\\b', ['Wat is wat tân?!']],
    ['\\bWat is dat/wat zijn dat\\b', ['Wah benne dattan']],
    ['\\bwe kwamen er aan\\b', ['we kwamme dur an']],
    ['\\bwe stonden\\b', ['we stinge']],
    ['\\bwedstrijd\\b', ['metse']],
    ['\\bWelja\\b', ['Beijaat']],
    ['\\bwerk\\b', ['werrek']],
    ['\\bwesp\\b', ['weps']],
    ['\\bwestside story\\b', ['wedstrijdstorie']],
    ['\\bzeuren\\b', ['zaikuh']],
    ['\\bziekenfonds\\b', ['siekefonst']],
    ['\\bziekte van Parkinson\\b', ['ziekte van Pakistan']],
    ['\\bzijlpoort\\b', ['zellepaurt']],
    ['\\bZo direct\\b', ['Aastons']],
    ['\\bzo meteen\\b', ['aanst', 'zobedeen']],
    ['\\bzweeg\\b', ['zwoog']],
    ['\\bzwerver\\b', ['zwerrever']]
]